# Generated by Django 6.0.3 on 2026-05-19 12:34

import apps.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('provenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeset',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Optional free-text note explaining the edit.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='citationinstance',
            name='locator',
            field=models.CharField(blank=True, db_default='', default='', max_length=200, validators=[apps.core.validators.validate_no_mojibake]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='citation',
            field=models.TextField(blank=True, db_default='', default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='claim',
            name='needs_review_notes',
            field=models.TextField(blank=True, db_default='', default='', help_text='Context for reviewers about why this claim needs attention.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddConstraint(
            model_name='changeset',
            constraint=models.CheckConstraint(condition=models.Q(('note__length__lte', 1000)), name='provenance_changeset_note_max_length'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(condition=models.Q(('citation__length__lte', 2000)), name='provenance_claim_citation_max_length'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(condition=models.Q(('needs_review_notes__length__lte', 2000)), name='provenance_claim_needs_review_notes_max_length'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 2000)), name='provenance_source_description_max_length'),
        ),
    ]
