# Generated by Django 6.0.3 on 2026-03-29 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("provenance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="retracted_by_changeset",
            field=models.ForeignKey(
                blank=True,
                help_text="The changeset that deactivated this claim (full_sync retraction).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retracted_claims",
                to="provenance.changeset",
            ),
        ),
        migrations.AlterField(
            model_name="changeset",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who made this edit. Null for source-level changesets.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="changesets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="IngestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set on completion (success, partial, or failure).",
                        null=True,
                    ),
                ),
                (
                    "input_fingerprint",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hash of the source dump used as input.",
                        max_length=255,
                    ),
                ),
                (
                    "git_sha",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Code version (git commit SHA) at run time.",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                (
                    "counts",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Run statistics: parsed, matched, created, asserted, retracted, rejected.",
                    ),
                ),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("errors", models.JSONField(blank=True, default=list)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingest_runs",
                        to="provenance.source",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="changeset",
            name="ingest_run",
            field=models.ForeignKey(
                blank=True,
                help_text="The ingest run that produced this changeset. Null for user edits.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="changesets",
                to="provenance.ingestrun",
            ),
        ),
    ]
