# Generated by Django 6.0.3 on 2026-03-29 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "provenance",
            "0002_claim_retracted_by_changeset_alter_changeset_user_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="changeset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("ingest_run__isnull", True), ("user__isnull", False)),
                    models.Q(("ingest_run__isnull", False), ("user__isnull", True)),
                    models.Q(("ingest_run__isnull", True), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="provenance_changeset_user_xor_ingest_run",
            ),
        ),
    ]
