# Generated by Django 6.0.3 on 2026-05-19 12:34

import apps.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='citationsource',
            name='description',
            field=models.TextField(blank=True, db_default='', default='', max_length=5000, validators=[apps.core.validators.validate_no_mojibake]),
        ),
        migrations.AddConstraint(
            model_name='citationsource',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 5000)), name='citation_citationsource_description_max_length'),
        ),
    ]
