# Generated by Django 6.0.3 on 2026-05-19 12:34

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='corporateentity',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='creditrole',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='displaysubtype',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='displaytype',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='gameformat',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='gameplayfeature',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, max_length=10000, validators=[apps.core.validators.validate_no_mojibake]),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='rewardtype',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='system',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='technologygeneration',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='technologysubgeneration',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='title',
            name='needs_review_notes',
            field=models.TextField(blank=True, help_text='Context for reviewers about why this title needs attention.', max_length=2000, validators=[apps.core.validators.validate_no_mojibake]),
        ),
        migrations.AddConstraint(
            model_name='cabinet',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 10000)), name='catalog_cabinet_description_max_length'),
        ),
        migrations.AddConstraint(
            model_name='corporateentity',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 10000)), name='catalog_corporateentity_description_max_length'),
        ),
        migrations.AddConstraint(
            model_name='creditrole',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 10000)), name='catalog_creditrole_description_max_length'),
        ),
        migrations.AddConstraint(
            model_name='displaysubtype',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 10000)), name='catalog_displaysubtype_description_max_length'),
        ),
        migrations.AddConstraint(
            model_name='displaytype',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 10000)), name='catalog_displaytype_description_max_length'),
        ),
        migrations.AddConstraint(
            model_name='franchise',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 10000)), name='catalog_franchise_description_max_length'),
        ),
        migrations.AddConstraint(
            model_name='gameformat',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 10000)), name='catalog_gameformat_description_max_length'),
        ),
        migrations.AddConstraint(
            model_name='gameplayfeature',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 10000)), name='catalog_gameplayfeature_description_max_length'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 10000)), name='catalog_location_description_max_length'),
        ),
        migrations.AddConstraint(
            model_name='machinemodel',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 10000)), name='catalog_machinemodel_description_max_length'),
        ),
        migrations.AddConstraint(
            model_name='manufacturer',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 10000)), name='catalog_manufacturer_description_max_length'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 10000)), name='catalog_person_description_max_length'),
        ),
        migrations.AddConstraint(
            model_name='rewardtype',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 10000)), name='catalog_rewardtype_description_max_length'),
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 10000)), name='catalog_series_description_max_length'),
        ),
        migrations.AddConstraint(
            model_name='system',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 10000)), name='catalog_system_description_max_length'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 10000)), name='catalog_tag_description_max_length'),
        ),
        migrations.AddConstraint(
            model_name='technologygeneration',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 10000)), name='catalog_technologygeneration_description_max_length'),
        ),
        migrations.AddConstraint(
            model_name='technologysubgeneration',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 10000)), name='catalog_technologysubgeneration_description_max_length'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 10000)), name='catalog_theme_description_max_length'),
        ),
        migrations.AddConstraint(
            model_name='title',
            constraint=models.CheckConstraint(condition=models.Q(('description__length__lte', 10000)), name='catalog_title_description_max_length'),
        ),
        migrations.AddConstraint(
            model_name='title',
            constraint=models.CheckConstraint(condition=models.Q(('needs_review_notes__length__lte', 2000)), name='catalog_title_needs_review_notes_max_length'),
        ),
    ]
