# Generated by Django 6.0.3 on 2026-03-27 12:57

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_corporateentity_ipdb_manufacturer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cabinet",
            name="name",
            field=models.CharField(
                max_length=200,
                unique=True,
                validators=[apps.core.validators.validate_no_mojibake],
            ),
        ),
        migrations.AlterField(
            model_name="corporateentity",
            name="name",
            field=models.CharField(
                help_text='Full corporate name, e.g., "D. Gottlieb & Company"',
                max_length=300,
                validators=[apps.core.validators.validate_no_mojibake],
            ),
        ),
        migrations.AlterField(
            model_name="creditrole",
            name="name",
            field=models.CharField(
                max_length=200,
                unique=True,
                validators=[apps.core.validators.validate_no_mojibake],
            ),
        ),
        migrations.AlterField(
            model_name="displaysubtype",
            name="name",
            field=models.CharField(
                max_length=200, validators=[apps.core.validators.validate_no_mojibake]
            ),
        ),
        migrations.AlterField(
            model_name="displaytype",
            name="name",
            field=models.CharField(
                max_length=200,
                unique=True,
                validators=[apps.core.validators.validate_no_mojibake],
            ),
        ),
        migrations.AlterField(
            model_name="franchise",
            name="name",
            field=models.CharField(
                max_length=200,
                unique=True,
                validators=[apps.core.validators.validate_no_mojibake],
            ),
        ),
        migrations.AlterField(
            model_name="gameformat",
            name="name",
            field=models.CharField(
                max_length=200,
                unique=True,
                validators=[apps.core.validators.validate_no_mojibake],
            ),
        ),
        migrations.AlterField(
            model_name="gameplayfeature",
            name="name",
            field=models.CharField(
                max_length=200,
                unique=True,
                validators=[apps.core.validators.validate_no_mojibake],
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=300,
                validators=[apps.core.validators.validate_no_mojibake],
            ),
        ),
        migrations.AlterField(
            model_name="machinemodel",
            name="name",
            field=models.CharField(
                max_length=300, validators=[apps.core.validators.validate_no_mojibake]
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(
                max_length=200,
                unique=True,
                validators=[apps.core.validators.validate_no_mojibake],
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(
                max_length=200, validators=[apps.core.validators.validate_no_mojibake]
            ),
        ),
        migrations.AlterField(
            model_name="rewardtype",
            name="name",
            field=models.CharField(
                max_length=200,
                unique=True,
                validators=[apps.core.validators.validate_no_mojibake],
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="name",
            field=models.CharField(
                max_length=200, validators=[apps.core.validators.validate_no_mojibake]
            ),
        ),
        migrations.AlterField(
            model_name="system",
            name="name",
            field=models.CharField(
                max_length=200,
                unique=True,
                validators=[apps.core.validators.validate_no_mojibake],
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=200,
                unique=True,
                validators=[apps.core.validators.validate_no_mojibake],
            ),
        ),
        migrations.AlterField(
            model_name="technologygeneration",
            name="name",
            field=models.CharField(
                max_length=200,
                unique=True,
                validators=[apps.core.validators.validate_no_mojibake],
            ),
        ),
        migrations.AlterField(
            model_name="technologysubgeneration",
            name="name",
            field=models.CharField(
                max_length=200, validators=[apps.core.validators.validate_no_mojibake]
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="name",
            field=models.CharField(
                max_length=200,
                unique=True,
                validators=[apps.core.validators.validate_no_mojibake],
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="name",
            field=models.CharField(
                max_length=300, validators=[apps.core.validators.validate_no_mojibake]
            ),
        ),
    ]
